petisco/controller/controller_decorator.py
petisco/use_case/use_case_logger.py
tests/unit/controller/test_controller_logger.py
tests/unit/use_case/test_use_case.py

Added a blacklist of types to use-case and controller decorator that prevents from logging undesirable objects such as Bytes. On contrary, it will substitute the object itself by a string containing its type name.

Added types blacklist when logging from use case decorator

---

petisco/domain/value_objects/string_value_object.py
tests/unit/domain/value_objects/test_string_value_object.py

To _ensure_value_contains_valid_char of StringValueObject
This can be used to prevent inserting not supported strings to MySQL DBs that
only support 3-byte UTF strings

Add optional flag allow_utf8mb4 (default: True) 

---

petisco/application/config/config_persistence.py
petisco/application/petisco.py
petisco/fixtures/persistence.py
petisco/modules/healthcheck/application/healthcheck_provider.py
petisco/persistence/sqlalchemy/sqlalchemy_persistence.py
petisco/persistence/sqlalchemy/sqlalchemy_persistence_connector.py
petisco/persistence/sqlalchemy/sqlalchemy_session_scope.py
tests/integration/flask_app/toy_app/config/config_persistence.py
tests/integration/flask_app/toy_app/infrastructure/repositories/sql_user_repository.py
tests/integration/flask_app/toy_app/infrastructure/repositories/user_model.py
tests/integration/flask_app/toy_app/petisco.yml
tests/unit/application/test_config.py
tests/unit/application/ymls/petisco.all.yml
tests/unit/application/ymls/petisco.events.nosubscribers.yml
tests/unit/application/ymls/petisco.noevents.yml

Currently Petisco doesn't support working with multiple SQL persistence sources.
In this proposal the persistence config is now defined as a list:
```
persistence:
- name: petisco
config: tests.integration.flask_app.toy_app.config.config_persistence.config_persistence
models:
user: tests.integration.flask_app.toy_app.infrastructure.repositories.user_model.UserModel
```
instead of:
```
persistence:
config: tests.integration.flask_app.toy_app.config.config_persistence.config_persistence
models:
user: tests.integration.flask_app.toy_app.infrastructure.repositories.user_model.UserModel
```
This way we could add multiple sources.
Then in our SQL repositories we have to explicitly select a persistence source when retrieving the models and when using a session:
```
class …
```

Proposal for multiple SQL persistence sources

---

README.md
petisco/application/petisco.py
petisco/fixtures/persistence.py
petisco/modules/healthcheck/application/healthcheck_provider.py
petisco/persistence/sqlalchemy/sqlalchemy_persistence.py
petisco/persistence/sqlalchemy/sqlalchemy_persistence_connector.py
petisco/persistence/sqlalchemy/sqlalchemy_session_scope.py
tests/integration/flask_app/test_flask_application.py
tests/integration/flask_app/test_flask_application_jwt_tokens_and_sqlalchemy_persistence.py
tests/integration/flask_app/toy_app/infrastructure/repositories/user_model.py

- Use a marker to provide persistence source name when using petisco_sql_database
fixture. If not provided defaults to "petisco"
- Change healthcheck behavior to take into account multiple persistence sources.
For the moment only do a healtcheck for SQL sources

Fix issues with multiple persistence sources

---

.github/workflows/pypi.yml

See:
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

Replace depecrated set-env in Github action

---

petisco/tasks/config/config_task.py
petisco/tasks/infrastructure/apscheduler_task_executor.py

See: #140
These tasks have a field "every" that admits a crontab expression to schedule
tasks
For example, with this config:
```yaml
cron:
every: "33 * * * *"
handler: taskmanager.src.modules.dummy.tasks.cron_task
```
The task `cron_task` will be executed every day and every hour at
the 33rd minute
More info on crontab expressions on webs like https://crontab.guru/

Add new task type "cron"

---

setup.py

SQLAlchemy 1.4.0 breaks Petisco persistence

Set required SQLAlchemy version [1.3.11,1.4.0)

---

petisco/domain/value_objects/string_value_object.py
requirements/dev.txt
requirements/requirements.txt
tests/modules/unit/domain/value_objects/test_string_value_object.py

Upgrade **pre-commit** version to enable black hook
> The hook `black` requires pre-commit version 2.9.2 but version 1.18.3 is installed
Upgrade **APScheduler** version due broken dependencies ([info](https://github.com/agronholm/apscheduler/issues/536))

Fix check of utf8mb4 characters in string value object guard

---

petisco/controller/controller_handler.py
petisco/persistence/elastic/apm_extension_is_installed.py
tests/modules/unit/controller/test_controller_handler.py

- :information_source: We use `elasticapm.set_custom_context` instead `elasticapm.label` because is information used for debugging and it is not indexed so we cannot do searches and dashboards based in this data (see [doc](https://www.elastic.co/guide/en/apm/get-started/current/metadata.html#custom-fields))
- **elastic-apm** dependency is defined in `requirements.txt`, so, it always will be installed. On this way, always will try to inject error response and trace in _APM_ if there is a transaction, else will ignore it

Inject error traces in apm

---

petisco/base/domain/errors/domain_error.py
tests/modules/base/domain/errors/unit/test_domain_error.py

The idea is avoid specify the detail in all errors that we define when the name is descriptive enough

ENH. Add default behaviour for get_specify_detail method of domain error

---

petisco/base/misc/wrapper.py
tests/modules/base/application/controller/unit/test_controller.py
tests/modules/extra/fastapi/controller/unit/test_fastapi_controller.py

I think the problem is in the wrapper, when an fastapi controller return an error, the fastapi result mapper raise an `HTTPException` and the middlware (after method) is not executed
> AssertionError: Expected 'after' to have been called
The solution is do the mapping after run middleware (after)
:memo: Note: There were doubts about this, notifier middleware only notifies `UnknownError` that are generated by unexpected errors (it does not notify controlled ones with correspondent domain errors..) I understand that this is the expected behaviour

FIX. Controller. Ensure run middleware (after) when result mapper raise an exception

---

petisco/base/application/use_case/use_case.py

When an error occurs inside of a use case, the exception is caught here and return a `Failure`, so controller wrapper does not capture exception in APM

feat(monitoring): add apm capture exception in use_case wrapper

---

.github/workflows/ci.macos.yml
.github/workflows/ci.yml
.github/workflows/coverage.yml
doc/message_broker/MessageBroker.md

- Add clone of the project to can run scripts
- Run scripts as modules to avoid import failures
In addition I have added any Markdown files to exclude in CI workflows ([doc](https://docs.github.com/es/actions/using-workflows/workflow-syntax-for-github-actions#patterns-to-match-file-paths)) (checked in this PR https://github.com/alice-biometrics/petisco/pull/249)

docs: improve message-broker readme

---

setup.py

fix: restrict Flask version to <=2.1.3

---

petisco/frameworks/flask/application/flask_application.py

Following this approach:
https://medium.com/ntropy-network/hiding-endpoints-from-swaggerui-while-supporting-with-connexion-960a6ede41cf

feat: hide "private"  paths from Swagger UI

---

petisco/extra/slack/application/notifier/exception_blocks_slack_notifier_message_converter.py

fix: avoid exception when traceback is None

---

petisco/event/shared/domain/event.py

As a result of these changes, the versions began to be published as integers in elastic instead of strings. Therefore, in petisco v0, event version parsing was broken.
https://github.com/alice-biometrics/petisco/pull/354/files#diff-ff664927556574395a1aa44764769a15701af0e32778a7c52811d9dfa816ae1c

fix: cast event version to int regardless of type

---

petisco/base/application/application.py
petisco/base/domain/message/message.py
petisco/cli/petisco.py
tests/modules/base/application/controller/unit/test_controller.py
tests/modules/base/application/test_application.py
tests/modules/base/domain/messages/unit/test_command.py
tests/modules/base/domain/messages/unit/test_domain_event.py
tests/modules/base/domain/messages/unit/test_message.py
tests/modules/extra/fastapi/controller/integration/test_fastapi_application.py

Naïve datetimes can provoke unexpected results with some methods that assume local times

fix: replace utcnow() with now(timezone.utc)

---

petisco/extra/rabbitmq/application/message/consumer/rabbitmq_message_consumer.py
tests/modules/extra/rabbitmq/application/message/consumer/test_rabbitmq_message_consumer.py

Current notifications are missing some information to ease debugging
With this change we would identify the subscribers that were associated with that consumer who lost the connection

feat: improve lost connection notifications in rabbitmq consumer

---

petisco/extra/rabbitmq/application/message/bus/rabbitmq_command_bus.py
petisco/extra/rabbitmq/application/message/bus/rabbitmq_domain_event_bus.py
petisco/extra/rabbitmq/application/message/bus/rabbitmq_message_publisher.py
tests/modules/extra/rabbitmq/application/message/bus/test_rabbitmq_domain_event_bus.py

You are only supposed to enable Confirms on the channel once (see: https://www.rabbitmq.com/tutorials/tutorial-seven-java#enabling-publisher-confirms-on-a-channel)
Since we create the channel on the publish method of the command and event buses I'm guessing this was only happening when publishing multiple commands/events

chore: avoid enabling confirm_delivery on channels more than once

---

petisco/base/domain/message/message.py
tests/modules/base/domain/messages/unit/test_message.py

Para poder definir BaseModels como atributos de eventos y que no pase esto:
```python
Traceback (most recent call last):
File "/usr/local/lib/python3.12/site-packages/petisco/base/application/use_case/meta_use_case.py", line 20, in wrapped
return method(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^
File "/app/app/src/kyc/selfie/upload/application/registration_selfie_uploader.py", line 84, in execute
injection_result = selfie_injection_check(
^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/meiga/decorators/early_return.py", line 31, in _early_return
return func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "/app/app/src/kyc/selfie/upload/application/selfie_injection/selfie_injection_check.py", line 42, in selfie_injection_check
return …
```

feat: allow base models as Message attributes
